### PR TITLE
Reuse secrets correctly

### LINKED ISSUE #309: Camunda8 - Helm Upgrade Fails
helm upgrade fails for 3 Times because of missing parameters and after that it fails completly.

**_helm upgrade camunda8 camunda8/camunda-platform --values values8.yaml_**

_Error: UPGRADE FAILED: execution error at (camunda-platform/charts/identity/templates/tasklist-secret.yaml:10:22): 
PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                 Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                 Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases

    'global.identity.auth.tasklist.existingSecret' must not be empty, please add '--set global.identity.auth.tasklist.existingSecret=$TASKLIST_SECRET' to the command. To get the current value:

        export TASKLIST_SECRET=$(kubectl get secret --namespace "default" "camunda8-tasklist-identity-secret" -o jsonpath="{.data.tasklist-secret}" | base64 --decode)_

_**export TASKLIST_SECRET=$(kubectl get secret --namespace "default" "camunda8-tasklist-identity-secret" -o jsonpath="{.data.tasklist-secret}" | base64 --decode)
helm upgrade camunda8 camunda8/camunda-platform --values values8.yaml --set global.identity.auth.tasklist.existingSecret=$TASKLIST_SECRET**_

_Error: UPGRADE FAILED: execution error at (camunda-platform/charts/identity/templates/optimize-secret.yaml:10:22): 
PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                 Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                 Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases

    'global.identity.auth.optimize.existingSecret' must not be empty, please add '--set global.identity.auth.optimize.existingSecret=$OPTIMIZE_SECRET' to the command. To get the current value:

        export OPTIMIZE_SECRET=$(kubectl get secret --namespace "default" "camunda8-optimize-identity-secret" -o jsonpath="{.data.optimize-secret}" | base64 --decode)_

_**export OPTIMIZE_SECRET=$(kubectl get secret --namespace "default" "camunda8-optimize-identity-secret" -o jsonpath="{.data.optimize-secret}" | base64 --decode)
helm upgrade camunda8 camunda8/camunda-platform --values values8.yaml --set global.identity.auth.tasklist.existingSecret=$TASKLIST_SECRET --set global.identity.auth.optimize.existingSecret=$OPTIMIZE_SECRET**_

Error: UPGRADE FAILED: execution error at (camunda-platform/charts/identity/templates/operate-secret.yaml:10:21): 
PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                 Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                 Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases

    'global.identity.auth.operate.existingSecret' must not be empty, please add '--set global.identity.auth.operate.existingSecret=$OPERATE_SECRET' to the command. To get the current value:

_**export OPERATE_SECRET=$(kubectl get secret --namespace "default" "camunda8-operate-identity-secret" -o jsonpath="{.data.operate-secret}" | base64 --decode)
helm upgrade camunda8 camunda8/camunda-platform --values values8.yaml --set global.identity.auth.tasklist.existingSecret=$TASKLIST_SECRET --set global.identity.auth.optimize.existingSecret=$OPTIMIZE_SECRET --set global.identity.auth.operate.existingSecret=$OPERATE_SECRET**_

_Error: UPGRADE FAILED: cannot patch "camunda8-identity" with kind Deployment: Deployment.apps "camunda8-identity" is invalid: [spec.template.spec.containers[0].env[4].valueFrom.secretKeyRef.name: Invalid value: "91PjdWKZ5p": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.template.spec.containers[0].env[7].valueFrom.secretKeyRef.name: Invalid value: "HFuYimnFrg": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.template.spec.containers[0].env[10].valueFrom.secretKeyRef.name: Invalid value: "7niyS1tPNi": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')] && cannot patch "camunda8-operate" with kind Deployment: Deployment.apps "camunda8-operate" is invalid: spec.template.spec.containers[0].env[4].valueFrom.secretKeyRef.name: Invalid value: "91PjdWKZ5p": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*') && cannot patch "camunda8-optimize" with kind Deployment: Deployment.apps "camunda8-optimize" is invalid: spec.template.spec.containers[0].env[8].valueFrom.secretKeyRef.name: Invalid value: "7niyS1tPNi": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*') && cannot patch "camunda8-tasklist" with kind Deployment: Deployment.apps "camunda8-tasklist" is invalid: spec.template.spec.containers[0].env[4].valueFrom.secretKeyRef.name: Invalid value: "HFuYimnFrg": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*') && cannot patch "camunda8-tasklist" with kind Ingress: admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: host "_" and path "/" is already defined in ingress default/camunda8-operate_

### PR DESCRIPTION
**Pull request by Zelldon**
Fixes some issues regarding the deployed secrets on the upgrade path, see this comment https://github.com/camunda/camunda-platform-helm/issues/309#issuecomment-1116014190 for further details

closes #309 

@oleschoenburg I did most changes I think you can already have a look. I will add the upgrade test we discussed tomorrow.

### CODE REVIEW

**Review by oleschoenburg — COMMENTED** [review]
I had an initial look and everything looks as I expected. I definitely want to wait for those test though because there's no way I'd spot an issue with the templates :laughing:

**Comment by Zelldon** [comment]
Ok this was a fight @oleschoenburg but I got it working :grin: I think it was great to add this, because I realized that if for example you set the secret to a wrong value your are not able to login anymore which is great :+1:

File: charts/camunda-platform/test/integration/integration_test.go [hunk 1]
```diff
@@ -92,6 +92,68 @@ func (s *integrationTest) TestServicesEnd2End() {
...
+		SetStrValues: map[string]string{
+			"global.identity.auth.tasklist.existingSecret": tasklistSecret,
+			"global.identity.auth.optimize.existingSecret": optimizeSecret,
+			"global.identity.auth.operate.existingSecret":  operateSecret,
+			"identity.keycloak.auth.adminPassword":  keycloakAdminPassword,
+			"identity.keycloak.auth.managementPassword":  keycloakManagementPassword,
+			"identity.keycloak.postgresql.auth.password":  postgresqlPassword,
+		},
+	}
+	helm.Upgrade(s.T(), upgradeOptions, s.chartPath, s.release)
```
Comment (oleschoenburg) [inline charts/camunda-platform/test/integration/integration_test.go:138]: :x: shouldn't we assert that this doesn't return an error? otherwise, the upgrade might fail silently and all the integration checks later will succeed only because the initial install was successful.

**Review by oleschoenburg — CHANGES_REQUESTED** [review]
In general this looks good and I like the test (so readable :+1: :1st_place_medal:).

File: charts/camunda-platform/test/integration/integration_test.go (hunk 1 above)
Comment (Zelldon) [reply charts/camunda-platform/test/integration/integration_test.go:138]: This is the difference between `helm.Upgrade` and `helm.UpgradeE`. The last one will return the error.

**Review by oleschoenburg — APPROVED** [review]

**Comment by Zelldon** [comment]
Thanks for the review @oleschoenburg :bow:
